version: '3' 
services: 
  rabbitmq: 
    image: "rabbitmq:latest" 
    environment:
      - RABBITMQ_DEFAULT_USER=guest 
      - RABBITMQ_DEFAULT_PASS=guest
    ports: 
      - "5672:5672" 
      - "15672:15672"
    networks: 
      - my_network 
  mysql: 
    image: "mysql:latest" 
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE : pubsub
      MYSQL_USER: root
    volumes: 
      - mysqldata:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports: 
      - "3306:3306"  
    networks: 
      - my_network

  redis: 
    image: "redis:latest" 
    ports: 
      - "6379:6379"
    networks: 
      - my_network 

  publisher: 
    build: 
      context: ./publisher
      dockerfile: Dockerfile 
    restart: always 
    depends_on: 
      - rabbitmq 
    environment: 
      RABBITMQ_ADDRESS: "rabbitmq:5672"

  consumer: 
    build: 
      context: ./consumer 
      dockerfile: Dockerfile 
    restart: always 
    depends_on: 
      - mysql 
      - redis 
      - rabbitmq 

    environment: 
      RABBITMQ_ADDRESS: "rabbitmq:5672" 
      MYSQL_CONNECTION_STRING: "root:password@tcp(mysql:3306)/pubsub?charset=utf8&parseTime=True&loc=Local"
      REDIS_ADDRESS: "redis:6379" 
      WEBSERVER_PORT: 8000 

networks: 
  my_network: 
    driver: bridge 

volumes: 
  mysqldata: 
