version: '3' 
services: 
  rabbitmq: 
    image: "rabbitmq:latest" 
    environment:
      - RABBITMQ_DEFAULT_USER=guest 
      - RABBITMQ_DEFAULT_PASS=guest
    ports: 
      - "5672:5672" 
      - "15672:15672"
  db: 
    image: "mysql:latest" 
    environment: 
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE : pubsub
      MYSQL_USER: mysql 
    volumes: 
      - mysqldata:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports: 
      - "3306:3306" 

  redis: 
    image: "redis:latest" 
    ports: 
      - "6379:6379"

  publisher: 
    build: 
      context: ./publisher
      dockerfile: Dockerfile 
    restart: on-failure
    depends_on: 
      - rabbitmq 
    environment: 
      RABBITMQ_ADDRESS: "rabbitmq:5672"
    

  consumer: 
    build: 
      context: ./consumer 
      dockerfile: Dockerfile 
    restart: always 
    ports: 
      - "8000:8000"
    links: 
      - db:database
    depends_on: 
      - db
      - redis 
      - rabbitmq 



volumes: 
  mysqldata: 
